name: Release

on:
  push:
    branches:
      - main  # Zmień na odpowiednią gałąź, jeśli to konieczne

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Install dependencies
        run: npm ci


      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

